version: "1"
services:
  lmql:
    image: 4mbroise/adbl2:latest
    ports:
      - 4000:4000
  
  api:
    image: 4mbroise/adbl2:api
    ports:
      - 10250:10250 
  
  frontend:
    image: 4mbroise/adbl2:ui
    ports:
      - 27019:27019
